//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hollow.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hollow.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Announcement_ActivityAnnouncement_Header {
            get {
                return ResourceManager.GetString("Announcement_ActivityAnnouncement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Announcement_GameAnnouncement_Header {
            get {
                return ResourceManager.GetString("Announcement_GameAnnouncement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Announcement_Loading {
            get {
                return ResourceManager.GetString("Announcement_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting announcements.
        /// </summary>
        internal static string Announcement_Loading_Message {
            get {
                return ResourceManager.GetString("Announcement_Loading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        internal static string GameSettings_Title {
            get {
                return ResourceManager.GetString("GameSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Home_Banners_Activity_Title {
            get {
                return ResourceManager.GetString("Home_Banners_Activity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Home_Banners_Info_Title {
            get {
                return ResourceManager.GetString("Home_Banners_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Home_Banners_Notice_Title {
            get {
                return ResourceManager.GetString("Home_Banners_Notice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string Home_StartGame {
            get {
                return ResourceManager.GetString("Home_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Not Found.
        /// </summary>
        internal static string Home_StartGameNotice_GameNotFound {
            get {
                return ResourceManager.GetString("Home_StartGameNotice_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        internal static string Home_StartGameNotice_NavigateToSettings {
            get {
                return ResourceManager.GetString("Home_StartGameNotice_NavigateToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        internal static string Screenshots_Title {
            get {
                return ResourceManager.GetString("Screenshots_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string Settings_About_GithubRepo {
            get {
                return ResourceManager.GetString("Settings_About_GithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Report.
        /// </summary>
        internal static string Settings_About_IssueReport {
            get {
                return ResourceManager.GetString("Settings_About_IssueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Settings_About_Privacy {
            get {
                return ResourceManager.GetString("Settings_About_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Settings_About_Version {
            get {
                return ResourceManager.GetString("Settings_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Settings_Subtitle_Game {
            get {
                return ResourceManager.GetString("Settings_Subtitle_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Settings_Subtitle_GameArguments {
            get {
                return ResourceManager.GetString("Settings_Subtitle_GameArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Settings_Subtitle_GameDirectory {
            get {
                return ResourceManager.GetString("Settings_Subtitle_GameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Subtitle_Language {
            get {
                return ResourceManager.GetString("Settings_Subtitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Settings_Subtitle_Storage {
            get {
                return ResourceManager.GetString("Settings_Subtitle_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Folder.
        /// </summary>
        internal static string Settings_Subtitle_Storage_OpenAppFolder {
            get {
                return ResourceManager.GetString("Settings_Subtitle_Storage_OpenAppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow supports only the UIGF v4.0 standard for providing and accepting ZZZ-related records.
        /// </summary>
        internal static string Settings_Uigf_Announcement {
            get {
                return ResourceManager.GetString("Settings_Uigf_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIGF organization member.
        /// </summary>
        internal static string Settings_Uigf_Member {
            get {
                return ResourceManager.GetString("Settings_Uigf_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About UIGF v4.0 Standard.
        /// </summary>
        internal static string Settings_Uigf_Standard {
            get {
                return ResourceManager.GetString("Settings_Uigf_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIGF Website.
        /// </summary>
        internal static string Settings_Uigf_Website {
            get {
                return ResourceManager.GetString("Settings_Uigf_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangboo Channel.
        /// </summary>
        internal static string SignalSearch_BangbooChannel {
            get {
                return ResourceManager.GetString("SignalSearch_BangbooChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string SignalSearch_Delete {
            get {
                return ResourceManager.GetString("SignalSearch_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record profile: .
        /// </summary>
        internal static string SignalSearch_Delete_Tip {
            get {
                return ResourceManager.GetString("SignalSearch_Delete_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Guarantee.
        /// </summary>
        internal static string SignalSearch_Detailed_InGuarantee {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_InGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string SignalSearch_Detailed_ItemType {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SignalSearch_Detailed_Name {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Type.
        /// </summary>
        internal static string SignalSearch_Detailed_RankType {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_RankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single / Consecutive.
        /// </summary>
        internal static string SignalSearch_Detailed_SingleOrConsecutive {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_SingleOrConsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive - {0} poll.
        /// </summary>
        internal static string SignalSearch_Detailed_SingleOrConsecutive_Consecutive {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_SingleOrConsecutive_Consecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string SignalSearch_Detailed_SingleOrConsecutive_Single {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_SingleOrConsecutive_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string SignalSearch_Detailed_Time {
            get {
                return ResourceManager.GetString("SignalSearch_Detailed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Channel.
        /// </summary>
        internal static string SignalSearch_ExclusiveChannel {
            get {
                return ResourceManager.GetString("SignalSearch_ExclusiveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string SignalSearch_Export {
            get {
                return ResourceManager.GetString("SignalSearch_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the UIDs to be exported:.
        /// </summary>
        internal static string SignalSearch_Export_Tip {
            get {
                return ResourceManager.GetString("SignalSearch_Export_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        internal static string SignalSearch_LoadGachaRecords_Analyze {
            get {
                return ResourceManager.GetString("SignalSearch_LoadGachaRecords_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load signal records.
        /// </summary>
        internal static string SignalSearch_LoadGachaRecords_GachaRecords {
            get {
                return ResourceManager.GetString("SignalSearch_LoadGachaRecords_GachaRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal records not found.
        /// </summary>
        internal static string SignalSearch_LoadGachaRecords_GachaRecordsNotFound {
            get {
                return ResourceManager.GetString("SignalSearch_LoadGachaRecords_GachaRecordsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string SignalSearch_Overview {
            get {
                return ResourceManager.GetString("SignalSearch_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string SignalSearch_Overview_Title {
            get {
                return ResourceManager.GetString("SignalSearch_Overview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Signals.
        /// </summary>
        internal static string SignalSearch_OverviewCard_ASignals {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_ASignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Signals.
        /// </summary>
        internal static string SignalSearch_OverviewCard_BSignals {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_BSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pity.
        /// </summary>
        internal static string SignalSearch_OverviewCard_Pity {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_Pity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S Average.
        /// </summary>
        internal static string SignalSearch_OverviewCard_SAverage {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_SAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S Signals.
        /// </summary>
        internal static string SignalSearch_OverviewCard_SSignals {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_SSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        internal static string SignalSearch_OverviewCard_Total {
            get {
                return ResourceManager.GetString("SignalSearch_OverviewCard_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string SignalSearch_ProhibitedCoverage_Loading {
            get {
                return ResourceManager.GetString("SignalSearch_ProhibitedCoverage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Channel.
        /// </summary>
        internal static string SignalSearch_StandardChannel {
            get {
                return ResourceManager.GetString("SignalSearch_StandardChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Search Records.
        /// </summary>
        internal static string SignalSearch_Title {
            get {
                return ResourceManager.GetString("SignalSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Channel.
        /// </summary>
        internal static string SignalSearch_UnknownChannel {
            get {
                return ResourceManager.GetString("SignalSearch_UnknownChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SignalSearch_Update {
            get {
                return ResourceManager.GetString("SignalSearch_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get singal records.
        /// </summary>
        internal static string SignalSearch_Update_GetRecordsFailed {
            get {
                return ResourceManager.GetString("SignalSearch_Update_GetRecordsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string SignalSearch_Update_Import {
            get {
                return ResourceManager.GetString("SignalSearch_Update_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0} records from page {1}.
        /// </summary>
        internal static string SignalSearch_Update_ProgressMessage {
            get {
                return ResourceManager.GetString("SignalSearch_Update_ProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting {0}.
        /// </summary>
        internal static string SignalSearch_Update_ProgressTitle {
            get {
                return ResourceManager.GetString("SignalSearch_Update_ProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal records updated.
        /// </summary>
        internal static string SignalSearch_Update_Success {
            get {
                return ResourceManager.GetString("SignalSearch_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records fetched, {1} records added.
        /// </summary>
        internal static string SignalSearch_Update_SuccessMessage {
            get {
                return ResourceManager.GetString("SignalSearch_Update_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string SignalSearch_Update_Url {
            get {
                return ResourceManager.GetString("SignalSearch_Update_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Caches.
        /// </summary>
        internal static string SignalSearch_Update_WebCaches {
            get {
                return ResourceManager.GetString("SignalSearch_Update_WebCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W-Engine Channel.
        /// </summary>
        internal static string SignalSearch_WEngineChannel {
            get {
                return ResourceManager.GetString("SignalSearch_WEngineChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Not Implemented.
        /// </summary>
        internal static string Special_ProhibitedCoverage_NotImplemented {
            get {
                return ResourceManager.GetString("Special_ProhibitedCoverage_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthKey not found, make sure Signal Search records are visited in game.
        /// </summary>
        internal static string Toast_AuthKeyNotFound_Message {
            get {
                return ResourceManager.GetString("Toast_AuthKeyNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Toast_Common_Error_Title {
            get {
                return ResourceManager.GetString("Toast_Common_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder named “ZenlessZoneZero Game”.
        /// </summary>
        internal static string Toast_InvalidGameDirectory_Message {
            get {
                return ResourceManager.GetString("Toast_InvalidGameDirectory_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Game Directory.
        /// </summary>
        internal static string Toast_InvalidGameDirectory_Title {
            get {
                return ResourceManager.GetString("Toast_InvalidGameDirectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Game Directory.
        /// </summary>
        internal static string Toast_UnknownGameDirectory_Message {
            get {
                return ResourceManager.GetString("Toast_UnknownGameDirectory_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No web caches found, make sure Signal Search records are visited in game.
        /// </summary>
        internal static string Toast_WebCachesNotFound_Message {
            get {
                return ResourceManager.GetString("Toast_WebCachesNotFound_Message", resourceCulture);
            }
        }
    }
}
