[package]
name = "hollow-launcher"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[[bin]]
name = "Hollow"
path = "src/main.rs"
windows_subsystem = "windows"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[build-dependencies]
winres = "0.1.12"