[package]
name = "hollow-launcher"
version = "0.0.5"
edition = "2021"
build = "build.rs"

[[bin]]
name = "Hollow"
path = "src/main.rs"
windows_subsystem = "windows"

[dependencies]

[build-dependencies]
winres = "0.1.12"